create table parcel (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    parcel_number VARCHAR(50) NOT NULL,
    delivery_date VARCHAR(8) NOT NULL,
    delivery_state VARCHAR(20) NOT NULL,
    address INTEGER
);

create table address (
    parcel INTEGER PRIMARY KEY REFERENCES parcel(id),
    street VARCHAR(250),
    zip VARCHAR(250),
    number VARCHAR(250),
    consignee VARCHAR(250)
);
